# File: lpic2_202_450_practice_tests.yaml
# Certification: LPIC-2 Certified Linux Engineer 202-450 Practice Exam Questions
certification_id: "lpic2-202-450"
certification_name: "LPIC-2 Certified Linux Engineer 202-450 Practice Exam"
certification_description: "LPIC-2 Certified Linux Engineer 202-450 Practice Exam Questions"
urls:
  - title: "Full Length Test Sets"
    description: "Full Length Practice Tests for LPIC-2 202-450"
    urls:
      full_test_1: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=fulllength&testset=1&test_id=3708"
      full_test_2: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=fulllength&testset=2&test_id=3708"
      full_test_3: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=fulllength&testset=3&test_id=3708"
  - title: "1. MISC Questions"
    description: "Practice Tests for MISC Questions"
    urls:
      test_set_1: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=1&test_id=3708"
      test_set_2: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=2&test_id=3708"
      test_set_3: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=3&test_id=3708"
      test_set_4: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=4&test_id=3708"
      test_set_5: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=5&test_id=3708"
      test_set_6: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=6&test_id=3708"
      test_set_7: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=7&test_id=3708"
      test_set_8: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=8&test_id=3708"
      test_set_9: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=9&test_id=3708"
      test_set_10: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=10&test_id=3708"
      test_set_11: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=11&test_id=3708"
      test_set_12: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=12&test_id=3708"
      test_set_13: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=13&test_id=3708"
      test_set_14: "https://{{ .BaseUrl }}/index.php?route=account/test/on&mode=practice&type=topicwise&topic=733&testset=14&test_id=3708"